version: "3"

services:
  source_postgres:
    container_name: source_postgres_container
    image: postgres:15
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: "${SOURCE_DB}"
      POSTGRES_USER: "${SOURCE_USER}"
      POSTGRES_PASSWORD: "${SOURCE_PASSWORD}"
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    container_name: destination_postgres_container
    image: postgres:15
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: "${DESTINATION_DB}"
      POSTGRES_USER: "${DESTINATION_USER}"
      POSTGRES_PASSWORD: "${DESTINATION_PASSWORD}"

  elt_script:
    build:
      context: ./elt_script # Directory containing the Dockerfile and elt_script.py
      dockerfile: Dockerfile # Name of the Dockerfile, if it's something other than "Dockerfile", specify here
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    environment:
      SOURCE_DB: "${SOURCE_DB}"
      SOURCE_USER: "${SOURCE_USER}"
      SOURCE_PASSWORD: "${SOURCE_PASSWORD}"
      DESTINATION_DB: "${DESTINATION_DB}" # Add this line
      DESTINATION_USER: "${DESTINATION_USER}" # Add this line
      DESTINATION_PASSWORD: "${DESTINATION_PASSWORD}" # Add this line
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  elt_network:
    driver: bridge
